### ISSUE TITLE
Tasks before deploying phase 1.1

### ISSUE THREAD

**Issue by betich** [isd-sgcu/rpkm66-frontend#25]
- [x] add กระติกน้ำ modal
- [x] validate form fields
- [x] connect apis
- [x] add navbar and footer to pages
- [x] error handling

**Comment by shalluv** [comment]
Do we not already validate form data on the backend side?

**Comment by betich** [comment]
best practice is to validate on both sides, but in our case we just need to output the backend validation.

**Comment by shalluv** [comment]
Naruhodo
